<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)



In [2]:
import numpy as np

## Creating Numpy Arrays from Python Lists

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
np.array([1, 2, 3, 4], dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [5]:
a1 = np.array([1, 2, 3, 4])
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
type(a2)

numpy.ndarray

In [7]:
a2.shape

(2, 3)

In [8]:
a2.ndim

2

In [9]:
a2.dtype

dtype('int64')

In [10]:
a2.size

6

Unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point)

Unlike Python lists, NumPy arrays can explicitly be **multi-dimensional**

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Creating Arrays from Scratch

### `zeros`, `ones`, `full`, `arange`, `linspace`

In [11]:
np.zeros([2, 4], dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (This is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
np.full((3, 5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [15]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### `random` 

In [16]:
np.random.random((4, 4))

array([[0.60246435, 0.11517272, 0.75746484, 0.80645864],
       [0.31665554, 0.09447633, 0.54599961, 0.75930017],
       [0.70215117, 0.7422159 , 0.70066427, 0.15656299],
       [0.34676825, 0.3639171 , 0.26356099, 0.1378449 ]])

In [17]:
# Seed for reproducibility
np.random.seed(0)
np.random.random((4, 4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [18]:
np.random.rand(4, 4)

array([[0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369]])

In [19]:
np.random.normal(0, 1, (3, 3))

array([[ 2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575]])

In [20]:
np.random.randint(0, 10, (4, 5))

array([[1, 7, 9, 9, 3],
       [6, 7, 2, 0, 3],
       [5, 9, 4, 4, 6],
       [4, 4, 3, 4, 4]])

### `eye`, `empty`

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## NumPy Array Attributes

- `itemsize`, which lists the size (in bytes) of each array element, and 
- `nbytes`, which lists the total size (in bytes) of the array

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Indexing & Slicing
### One-dimensional subarray

In [21]:
x1 = np.random.randint(20, size=6)
x1

array([ 8, 14, 15,  3, 15, 13])

In [22]:
x1[1]

np.int64(14)

### Slicing:
`x[start:stop:step]`

In [23]:
x1[0:3]

array([ 8, 14, 15])

In [24]:
x1[2:4]

array([15,  3])

In [25]:
# every other element, every 2 step
x1[::2]

array([ 8, 15, 15])

### Multi-dimensional array

In [26]:
x2 = np.random.randint(10, size=(3, 4))
x2

array([[5, 5, 0, 1],
       [5, 9, 3, 0],
       [5, 0, 1, 2]])

In [27]:
x2[1, 2]

np.int64(3)

In [28]:
x2[1, 2] = 6
x2

array([[5, 5, 0, 1],
       [5, 9, 6, 0],
       [5, 0, 1, 2]])

In [29]:
# Tow rows, three columns
x2[:2, :3]

array([[5, 5, 0],
       [5, 9, 6]])

In [30]:
x2[:, :2]

array([[5, 5],
       [5, 9],
       [5, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Reshaping of Arrays & Transpose

In [33]:
grid = np.arange(1, 10)
grid.shape

(9,)

In [ ]:
grid.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
x = np.array([1, 2, 3])
x.shape

(3,)

In [38]:
x.reshape(1, 3).shape

(1, 3)

In [42]:
x1 = np.array([[1, 2], [3, 4]])
x1.T

array([[1, 3],
       [2, 4]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Concatenation and Splitting

In [46]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate((x, y))

array([1, 2, 3, 3, 2, 1])

In [47]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.concatenate((grid, grid), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [51]:
# vstack
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [4, 5, 6]])
np.vstack((x, grid))

array([[1, 2, 3],
       [9, 8, 7],
       [4, 5, 6]])

In [53]:
# hstack
y = np.array([[99], [999]])
np.hstack((y, grid))

array([[ 99,   9,   8,   7],
       [999,   4,   5,   6]])

### Splitting of arrays

In [ ]:
x = np.array([1, 2, 3, 4, 55, 667, 223, 423])
np.split(x, [3, 5])

[array([1, 2, 3]), array([ 4, 55]), array([667, 223, 423])]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.

![image-broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

In [56]:
a = np.arange(3)
a

array([0, 1, 2])

In [ ]:
a + 5  # Broadcasting

array([5, 6, 7])

In [59]:
b = np.ones((3, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
c = np.arange(3).reshape((3, 1))
c

array([[0],
       [1],
       [2]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Manipulating & Comparing Arrays

### Aggregation
Aggregation = preform the same operation on a number of things


In [ ]:
list_number = [1, 2, 3]
ll = np.array(list_number)

In [66]:
massive_arr = np.random.random(10000)
massive_arr.shape

(10000,)

In [67]:
%timeit sum(massive_arr)
%timeit np.sum(massive_arr)

532 μs ± 10 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
3.5 μs ± 28.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [68]:
dogs_height = np.array([600, 470, 170, 430, 300])
np.std(dogs_height)

np.float64(147.32277488562318)

In [ ]:
np.var(dogs_height)

In [69]:
np.sqrt(np.var(dogs_height))

np.float64(147.32277488562318)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Sorting Arrays

np.sort uses an quicksort algorithm


In [70]:
x = np.array([2, 3, 1, 24, 91294, 1293849, 23, 4, 5, 2, 4, 5, 6, 2])
np.sort(x)

array([      1,       2,       2,       2,       3,       4,       4,
             5,       5,       6,      23,      24,   91294, 1293849])

In [71]:
# A related function is argsort, which instead returns the indices of sorted elements.
np.argsort(x)

array([ 2,  0, 13,  9,  1, 10,  7,  8, 11, 12,  6,  3,  4,  5])

### Sorting along rows or columns
NumPy's sorting algorithms is the ability to sort along specific rows or columns of a multidimensional array using the axis argument

In [73]:
np.random.seed(42)

MatA = np.random.randint(0, 10, size=(4, 6))
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [75]:
np.sort(MatA, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

### Partial Sorts: Partitioning

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [76]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[6, 5], [4, 3], [2, 1]])

# A(3x3) dot product B(3x2)
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [77]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [78]:
# B(2x3) dot A(3x3)
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [79]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

### Dot Product Example

In [81]:
# Number of jars sold
np.random.seed(0)

sale_amounts = np.random.randint(20, size=(5, 3))
sale_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [82]:
# Create weekly_saves DataFrames
import pandas as pd

weekly_sales = pd.DataFrame(
    sale_amounts,
    index=["Mon", "Tues", "Web", "Thurs", "Fri"],
    columns=["Almond Butter", "Peanut Butter", "Cashew Butter"],
)
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Web                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [85]:
# Create a price array

prices = np.array([[10, 8, 12]])
butter_prices = pd.DataFrame(
    prices,
    index=["Price"],
    columns=["Almond Butter", "Peanut Butter", "Cashew Butter"],
)
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [87]:
total_prices= weekly_sales.dot(butter_prices.T)
total_prices

Price
Mon      240
Tues     138
Web      458
Thurs    232
Fri      142

In [88]:
weekly_sales['Total Price'] = total_prices

In [89]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total Price
Mon               12             15              0          240
Tues               3              3              7          138
Web                9             19             18          458
Thurs              4              6             12          232
Fri                1              6              7          142